apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: deluge
spec:
  serviceName: "deluge"
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: deluge
  template:
    metadata:
      labels:
        app: deluge
    spec:
      containers:
        - image: ghcr.io/linuxserver/deluge
          name: deluge
          ports:
            - containerPort: 8112
            - containerPort: 6881
          env:
            - name: TZ
              value: "Asia/Kolkata"
          volumeMounts:
            - mountPath: /downloads
              name: deluge-downloads
            - mountPath: /config
              name: deluge-config
      volumes:
        - name: deluge-downloads
          persistentVolumeClaim:
            claimName: deluge-downloads
        - name: deluge-config
          persistentVolumeClaim:
            claimName: deluge-config
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: apache
spec:
  serviceName: "httpd"
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
        - image: httpd:alpine
          name: apache
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /usr/local/apache2/htdocs/
              name: deluge-downloads
      volumes:
        - name: deluge-downloads
          persistentVolumeClaim:
            claimName: deluge-downloads

